# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='category_id',
            new_name='category',
        ),
    ]
