# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0003_auto_20170323_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
    ]
