# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0004_auto_20170323_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attr',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='attr_val',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
