# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0007_auto_20170323_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='domain',
            new_name='monitoring',
        ),
    ]
