# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0009_auto_20170324_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
