# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0012_auto_20170327_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('monitoree.category',),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('monitoree.category',),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Scraped'), (3, 'Ignore')]),
        ),
    ]
