# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0015_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_image_scraped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, True), (2, 'Scraped'), (3, 'Ignore')], max_length=3),
        ),
    ]
