# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0016_auto_20170329_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_scrapped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, True), (2, 'Scraped'), (3, 'Ignore')]),
        ),
    ]
