# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0019_item_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_scrapped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
