# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0020_auto_20170329_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_scrapped',
            new_name='is_scraped',
        ),
    ]
