# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0022_auto_20170330_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Scraped'), (2, 'Ignore')]),
        ),
    ]
