# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0023_auto_20170331_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Scraped'), (2, 'Item Created'), (3, 'Image Downloaded'), (4, 'Image Uploaded'), (5, 'Completed')]),
        ),
    ]
