# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0024_auto_20170331_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
