# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoree', '0026_auto_20170401_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='vendor_attribute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='vendor_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
